// src/lib/seedData.ts
// Pre-loaded job data extracted from AI Jobs.xlsx — imported on first login
import { collection, addDoc, Timestamp } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { Job } from '@/types';

const SEED_JOBS: Omit<Job, 'id'>[] = [
  {
    company: 'Capital One',
    title: 'Director Product Management - Enterprise AI',
    description: 'Leader in financial tech; focuses on "Associate Experience" to simplify AI workflows. Great local McLean hub.',
    location: 'McLean, VA',
    salary: '$230,400 - $263,000',
    status: 'Ready to Apply',
    resumeType: 'Leader',
    jobUrl: 'https://www.capitalonecareers.com/job/mclean/director-product-management-enterprise-ai/1732/74521034320',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Stripe',
    title: 'Learning Architect',
    description: 'Gold standard for developer-centric infrastructure. Values high-performance "Stripe-y" culture and engineering excellence.',
    location: 'San Francisco, CA',
    salary: '$175,000 - $240,000',
    status: 'Applied',
    resumeType: 'Regular',
    jobUrl: 'https://stripe.com/jobs/listing/learning-architect/6154321',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'AWS',
    title: 'Sr. Manager, GenAI Strategy',
    description: 'Leading the GenAI Innovation Center for the largest cloud provider. Unmatched scale to influence "art of the possible."',
    location: 'Arlington, VA',
    salary: '$201,000 - $272,000',
    status: 'Wishlist',
    resumeType: 'Leader',
    jobUrl: 'https://www.amazon.jobs/en/jobs/2654321/sr-manager-gen-ai-strategy',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Proofpoint',
    title: 'AI Program Manager - Developer',
    description: 'Cybersecurity leader. Hybrid leadership + builder role focused on building agentic workflows for services.',
    location: 'Sunnyvale, CA',
    salary: '$160,000 - $210,000',
    status: 'Wishlist',
    resumeType: 'Builder',
    jobUrl: 'https://proofpoint.wd5.myworkdayjobs.com/en-US/ProofpointCareers/job/AI-Program-Manager---Developer_R14108',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Adobe',
    title: 'Sr. Applied AI Product Manager',
    description: 'Building an "Agentic operating layer" for Digital Media. Perfect for Zero-to-One builders inside an innovation giant.',
    location: 'San Jose, CA',
    salary: '$180,000 - $265,000',
    status: 'Wishlist',
    resumeType: 'Builder',
    jobUrl: 'https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced/job/Sr-Applied-AI-Product-Manager_R163097',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Okta',
    title: 'Digital Content & AI Automation Manager',
    description: 'Focused on "Vibe Marketing" and content as process-as-code. Great for tinkerer-architects.',
    location: 'Remote',
    salary: '$160,000 - $215,000',
    status: 'Wishlist',
    resumeType: 'Builder',
    jobUrl: 'https://www.okta.com/company/careers/marketing/digital-content-ai-automation-manager-7523533/',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Reltio',
    title: 'Director, AI GTM Strategy & Enablement',
    description: 'Pioneer in Data Unification. High-autonomy "tinkerer" role ideal for deconstructing GTM lifecycles.',
    location: 'Redwood Shores, CA',
    salary: '$190,000 - $230,000',
    status: 'Wishlist',
    resumeType: 'Leader',
    jobUrl: 'https://job-boards.greenhouse.io/reltio/jobs/5875187004',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Blackboard',
    title: 'AI Product Engineer',
    description: 'EdTech leader bridging pedagogy and software production. Mission-driven to improve learning.',
    location: 'Boca Raton, FL',
    salary: '$150,000 - $195,000',
    status: 'Applied',
    resumeType: 'Builder',
    jobUrl: 'https://careers.anthology.com/jobs/17436102-ai-product-engineer',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Workday',
    title: 'Product Advisor - Deployment Innovation',
    description: 'Cloud ERP leader with a massive local Reston presence. Focuses on scaling and automating deployment.',
    location: 'Reston, VA',
    salary: '$165,000 - $220,000',
    status: 'Applied',
    resumeType: 'Regular',
    jobUrl: 'https://workday.wd5.myworkdayjobs.com/en-US/Workday/job/Product-Advisor--Deployment-Innovation_JR-0106657-1',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'LINQ',
    title: 'Principal TPM, AI Enablement',
    description: 'Helping K-12 districts do more with less via AI systems. Combines learning science and practical shipping.',
    location: 'Wilmington, NC',
    salary: 'Not listed',
    status: 'Applied',
    resumeType: 'Leader',
    jobUrl: 'https://linq.com/careers',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Genesys',
    title: 'Principal, AI Enablement',
    description: 'Leader in Experience as a Service (EaaS). Transforming global departments via automated workflows.',
    location: 'Menlo Park, CA',
    salary: '$180,000 - $240,000',
    status: 'Applied',
    resumeType: 'Leader',
    jobUrl: 'https://genesys.wd1.myworkdayjobs.com/en-US/Genesys/job/Principal--Operational-Excellence-and-AI-Enablement_JR110249-1',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Automattic',
    title: 'AI Ops Manager',
    description: 'People behind WordPress. Building an AI-native culture for a distributed open-source organization.',
    location: 'New York, NY',
    salary: '$180,000 - $250,000',
    status: 'Wishlist',
    resumeType: 'Leader',
    jobUrl: 'https://automattic.com/work-with-us/job/ai-ops-manager-new-york/',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Applied Systems',
    title: 'AI Enablement Services Lead',
    description: 'Injecting AI into SaaS implementation. Redefining professional services in the insurance industry.',
    location: 'University Park, IL',
    salary: '$170,000 - $220,000',
    status: 'Wishlist',
    resumeType: 'Leader',
    jobUrl: 'https://careers-appliedsystems.icims.com/jobs/7462/ai-enablement-services-lead/job',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Dynatrace',
    title: 'Sr. AI Product Manager',
    description: 'Leader in observability. Focuses on "Applied AI" to automate corporate functions and manual tasks.',
    location: 'Waltham, MA',
    salary: '$175,000 - $235,000',
    status: 'Wishlist',
    resumeType: 'Builder',
    jobUrl: 'https://www.dynatrace.com/careers/jobs/1370163900/',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    company: 'Headspace',
    title: 'Director, AI Enablement',
    description: 'Reports to COO/Founder. Focus on mental health and safe AI-first operations.',
    location: 'Santa Monica, CA',
    salary: '$177,100 - $250,000',
    status: 'Wishlist',
    resumeType: 'Leader',
    jobUrl: '',
    coverLetterId: '',
    appliedDate: null,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export async function seedJobsForUser(uid: string) {
  const jobsRef = collection(db, 'jobSearchUsers', uid, 'jobs');
  for (const job of SEED_JOBS) {
    await addDoc(jobsRef, job);
  }
}
